POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Web development guide",
  "authot": "John Doe",
  "url": "https://example.com/web-development-guide",
  "likes": 0
}
